### ISSUE TITLE
playList does not name a type

### ISSUE THREAD

**Issue by schreibfaul1** [CelliesProjects/eStreamPlayer32#12]
Hi Cellie,
the error mentioned in the title occurs when compiling. Class and object have the same name. I program in Eclispse. Somehow the compiler doesn't like that. After renaming the object e.g.
```
playList playLi;
```
The error disappears. I have an Apache2 server. The eStreamPlayer then runs right away. Thanks for sharing this cool project.

**Comment by CelliesProjects** [comment]
Classes and objects do not (or rather should not according to the standard) share namespace.
Not really sure how to solve. Stay tuned.

**Comment by schreibfaul1** [comment]
That's right, the namespace is different. Nevertheless, when I name the object back via the refractor, the error comes back.
`"Type of problem: Shadowing New element playList Confilicting element type: Constructor"`
![image](https://user-images.githubusercontent.com/26044260/111062701-c89d7080-84aa-11eb-8e0f-8e8c74617e02.png)

**Comment by CelliesProjects** [comment]
Should be fixed.
